# define postgres
services:
  app:
    build: backend
    image: personal_finance
    ports:
      - "4000:4000"
    env_file: 
      - .app.env
    depends_on:
      - postgres
    profiles:
      - prod
  frontend:
    build: frontend
    image: personal_finance_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://app:4000
    depends_on:
      - app
    profiles:
      - prod
  postgres:
    image: postgres:12
    container_name: db
    env_file:
      - .db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      personal_finance_network:
        aliases:
          - db
    profiles:
      - db
      - prod

networks:
  personal_finance_network:
    driver: bridge
volumes:
  postgres-data:
