# define postgres
services:
  app:
    build:
      context: ./java-backend
    image: personal_finance_backend
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .app.env
    depends_on:
      - postgres
    networks:
      - personal_finance_network
    profiles:
      - prod
  frontend:
    build: frontend
    image: personal_finance_frontend
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://app:8080
    depends_on:
      - app
    networks:
      - personal_finance_network
    profiles:
      - prod
  postgres:
    image: postgres:12
    container_name: db
    env_file:
      - .db.env
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      personal_finance_network:
        aliases:
          - db
    profiles:
      - db
      - prod

networks:
  personal_finance_network:
    driver: bridge
volumes:
  postgres-data:
