import { Transaction, Category, UploadFile } from '../types';

export const mockUsers = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    password: 'password123',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    password: 'password123',
  },
  {
    id: '3',
    name: 'Bob Johnson',
    email: 'bob@example.com',
    password: 'password123',
  },
];

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Groceries',
    macroCategory: 'Food & Dining',
    regexPatterns: [
      '.*supermarket.*',
      '.*grocery.*',
      '.*food.*store.*',
    ],
  },
  {
    id: '2',
    name: 'Restaurants',
    macroCategory: 'Food & Dining',
    regexPatterns: [
      '.*restaurant.*',
      '.*cafe.*',
      '.*coffee.*shop.*',
    ],
  },
  {
    id: '3',
    name: 'Transportation',
    macroCategory: 'Transportation',
    regexPatterns: [
      '.*uber.*',
      '.*lyft.*',
      '.*taxi.*',
      '.*public.*transport.*',
    ],
  },
  {
    id: '4',
    name: 'Utilities',
    macroCategory: 'Bills & Utilities',
    regexPatterns: [
      '.*electric.*',
      '.*water.*',
      '.*gas.*',
      '.*internet.*',
      '.*phone.*',
    ],
  },
  {
    id: '5',
    name: 'Entertainment',
    macroCategory: 'Entertainment',
    regexPatterns: [
      '.*netflix.*',
      '.*spotify.*',
      '.*movie.*',
      '.*concert.*',
    ],
  },
  {
    id: '6',
    name: 'Salary',
    macroCategory: 'Income',
    regexPatterns: ['.*salary.*', '.*payroll.*'],
  },
  {
    id: '7',
    name: 'Business',
    macroCategory: 'Income',
    regexPatterns: ['.*business.*income.*'],
  },
  {
    id: '8',
    name: 'Investment',
    macroCategory: 'Income',
    regexPatterns: ['.*investment.*', '.*dividend.*'],
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    date: '2024-03-15',
    description: 'Whole Foods Market',
    amount: -85.32,
    account: 'Chase Checking',
    categoryId: '1',
    included: true,
  },
  {
    id: '2',
    date: '2024-03-14',
    description: 'Starbucks Coffee',
    amount: -4.95,
    account: 'Chase Checking',
    categoryId: '2',
    included: true,
  },
  {
    id: '3',
    date: '2024-03-13',
    description: 'Uber Ride',
    amount: -15.50,
    account: 'Chase Checking',
    categoryId: '3',
    included: true,
  },
  {
    id: '4',
    date: '2024-03-12',
    description: 'Electric Bill',
    amount: -120.00,
    account: 'Chase Checking',
    categoryId: '4',
    included: true,
  },
  {
    id: '5',
    date: '2024-03-11',
    description: 'Netflix Subscription',
    amount: -14.99,
    account: 'Chase Checking',
    categoryId: '5',
    included: true,
  },
  {
    id: '6',
    date: '2024-03-10',
    description: 'Trader Joe\'s',
    amount: -65.78,
    account: 'Chase Checking',
    categoryId: '1',
    included: true,
  },
  {
    id: '7',
    date: '2024-03-09',
    description: 'Italian Restaurant',
    amount: -45.20,
    account: 'Chase Checking',
    categoryId: '2',
    included: true,
  },
  {
    id: '8',
    date: '2024-03-08',
    description: 'Public Transport',
    amount: -2.75,
    account: 'Chase Checking',
    categoryId: '3',
    included: true,
  },
  {
    id: '9',
    date: '2024-03-07',
    description: 'Internet Bill',
    amount: -79.99,
    account: 'Chase Checking',
    categoryId: '4',
    included: true,
  },
  {
    id: '10',
    date: '2024-03-06',
    description: 'Spotify Premium',
    amount: -9.99,
    account: 'Chase Checking',
    categoryId: '5',
    included: true,
  },
  {
    id: '11',
    date: '2024-03-05',
    description: 'Local Grocery Store',
    amount: -32.45,
    account: 'Chase Checking',
    categoryId: '1',
    included: false,
  },
  {
    id: '12',
    date: '2024-03-04',
    description: 'Coffee Shop',
    amount: -3.50,
    account: 'Chase Checking',
    categoryId: '2',
    included: false,
  },
  {
    id: '13',
    date: '2024-03-03',
    description: 'Lyft Ride',
    amount: -12.30,
    account: 'Chase Checking',
    categoryId: '3',
    included: false,
  },
  {
    id: '14',
    date: '2024-03-02',
    description: 'Phone Bill',
    amount: -45.00,
    account: 'Chase Checking',
    categoryId: '4',
    included: false,
  },
  {
    id: '15',
    date: '2024-03-01',
    description: 'Movie Theater',
    amount: -25.00,
    account: 'Chase Checking',
    categoryId: '5',
    included: false,
  },
  {
    id: '16',
    date: '2024-03-15',
    description: 'March Salary',
    amount: 3500.00,
    account: 'Chase Checking',
    categoryId: '6',
    included: true,
  },
  {
    id: '17',
    date: '2024-03-10',
    description: 'Freelance Business Income',
    amount: 1200.00,
    account: 'Chase Checking',
    categoryId: '7',
    included: true,
  },
  {
    id: '18',
    date: '2024-03-05',
    description: 'Investment Dividend',
    amount: 250.00,
    account: 'Chase Savings',
    categoryId: '8',
    included: true,
  },
];

export const mockUploads: UploadFile[] = [
  {
    id: '1',
    filename: 'chase_march_2024.csv',
    account: 'Chase Checking',
    status: 'completed',
    uploadedAt: '2024-03-15T10:30:00Z',
    processedAt: '2024-03-15T10:35:00Z',
  },
  {
    id: '2',
    filename: 'amex_april_2024.csv',
    account: 'Amex Platinum',
    status: 'pending',
    uploadedAt: '2024-04-01T09:15:00Z',
  },
  {
    id: '3',
    filename: 'chase_feb_2024.csv',
    account: 'Chase Checking',
    status: 'error',
    uploadedAt: '2024-02-28T14:20:00Z',
    errorMessage: 'Invalid date format in row 12',
  },
  {
    id: '4',
    filename: 'savings_q1_2024.xlsx',
    account: 'Chase Savings',
    status: 'processing',
    uploadedAt: '2024-04-02T11:45:00Z',
  },
]; 