name: personal-finance-db
services:
  postgresql:
    image: postgres:16.4
    environment:
      - POSTGRES_USER=personalfinance_root
      - POSTGRES_PASSWORD=personalfinance_pwd
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=personalfinance_db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 127.0.0.1:5432:5432
