# define postgres
services:
  postgres:
    image: postgres:12
    container_name: db
    environment:
      POSTGRES_USER: personal_finance
      POSTGRES_PASSWORD: personal_finance_pwd
      POSTGRES_DB: personal_finance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - personal_finance_network

networks:
  personal_finance_network:
    driver: bridge
volumes:
  postgres-data:
