ALTER TABLE category_matchers
DROP CONSTRAINT category_matchers_pkey;

-- 2. Add the new auto-incrementing ID column
-- (Using modern PostgreSQL 10+ identity syntax. It automatically populates existing rows)
ALTER TABLE category_matchers
ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
ADD COLUMN IF NOT EXISTS year INTEGER;

-- 3. Set the new 'id' column as the Primary Key
ALTER TABLE category_matchers
ADD CONSTRAINT category_matchers_pkey PRIMARY KEY (id);


